#!/bin/bash

FILE=tests/run/List.lean
THEOREM_REGEX='theorem|instance'

text="$(awk '{ if(start) print; if($0 ~ "END PRELUDE") start=1; }' "$FILE")"
total=$(echo "$text" | grep -E "$THEOREM_REGEX" | wc -l)
skipped_trivial=$(echo "$text" | grep -E "SKIP TRIV" | wc -l)
skipped_not_applicable=$(echo "$text" | grep -E "SKIP NA" | wc -l)
successful_only_with_induction=$(echo "$text" | grep -E "IND" | wc -l)
unsuccessful=$(echo "$text" | grep -E "sorry" | wc -l)

candidates=$(($total - $skipped_trivial - $skipped_not_applicable))
successful_with_induction=$(($candidates - $unsuccessful))
successful_without_induction=$(($successful_with_induction - $successful_only_with_induction))
success_rate_without_induction=$(echo "$successful_without_induction / $candidates" | bc -l)
success_rate_with_induction=$(echo "$successful_with_induction / $candidates" | bc -l)

echo "Total number of 'theorem'/'instance' commands (outside of the prelude): $total"
echo "Skipped trivial commands: $skipped_trivial"
echo "Skipped non-applicable commands: $skipped_not_applicable"
echo ""
echo "Goals on which Aesop was run: $candidates"
echo "Goals which Aesop cannot solve: $unsuccessful"
echo "Goals which Aesop can solve without induction: $successful_without_induction"
echo "Success rate without induction: $success_rate_without_induction"
echo "Goals which Aesop can solve with induction: $successful_with_induction"
echo "Success rate with induction: $success_rate_with_induction"
