name = "aesop"
defaultTargets = ["Aesop"]
testDriver = "AesopTest"
precompileModules = false # We would like to turn this on, but it breaks the Mathlib cache.
platformIndependent = true

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "Aesop"

[[lean_lib]]
name = "AesopTest"
globs = ["AesopTest.+"]
leanOptions = {linter.unusedVariables = false}
