#!/usr/bin/env bash

# Usage:
#
# `./test` to build tests/*.lean
# `./test tests/A.lean tests/B.lean ...` to build the specified files
#
# This script must be called from the directory it is located in.

GREEN="\e[0;92m"
RESET="\e[0m"

lake build
[ "$?" -eq 0 ] || exit 1

if [ -z "$1" ]; then
  files="tests/*.lean"
else
  files="$@"
fi

failed=0

for file in ${files[@]}; do
  echo -e "$GREEN$file$RESET"
  lake env lean $file
  [ "$?" -eq 0 ] || failed=1
done

exit $failed
