#!/usr/bin/env bash

# Usage:
#
# `./test` to build tests/*.lean
# `./test tests/run/A.lean tests/golden/B.lean ...` to build the specified files
#
# This script must be called from the directory it is located in.

GREEN="\e[0;92m"
RESET="\e[0m"

LEAN_OPTS="-D linter.unusedVariables=false"

lake build std || exit 1 # required for tests/run/Aesop.lean
lake build Aesop AesopTest || exit 1

if [ -z "$1" ]; then
  files=(tests/run/*.lean)
  files+=(tests/golden/*.lean)
else
  files="$@"
fi

function run_run_test {
  lake env lean $LEAN_OPTS "$file"
  return "$?"
}

function run_golden_test {
  file="$1"
  expected="${file}.expected"
  produced="${file}.produced"
  lake env lean $LEAN_OPTS "$file" &> "$produced"
  if [ -f "$expected" ]; then
    diff "$expected" "$produced"
    return "$?"
  else
    echo "$expected not found, copying produced output"
    cp "$produced" "$expected"
    return 0
  fi
}

failed=0

for file in ${files[@]}; do
  echo -e "$GREEN$file$RESET"
  dir="$(dirname "$file")"
  case $dir in
    "tests/run")
      run_run_test "$file"
      [ "$?" -eq 0 ] || failed=1
      ;;
    "tests/golden")
      run_golden_test "$file"
      [ "$?" -eq 0 ] || failed=1
      ;;
    *)
      echo "Unexpected test file. Valid files are 'tests/run/*.lean' and 'tests/golden/*.lean'"
      exit 1
      ;;
  esac
done

exit $failed
